export {default as cuspedTorusSet} from "./cuspedTorus/set.js";
export {default as orbiTorusSet} from "./orbiTorus/set.js";
export {default as planeSet} from "./plane/set.js";
export {default as zLoopSet} from "./zLoop/set.js";
export {default as horizontalLoopSet} from "./horizontalLoop/set.js";
export {default as genus2Set} from "./genus2/set.js";
export {default as quotientGenus2Set} from "./quotientGenus2/set.js";
export {default as horizontalQuotientGenus2Set} from "./horizontalQuotientGenus2/set.js";
export {default as variableHeightQuotientGenus2Set} from "./variableHeightQuotientGenus2/set.js";
